import dbConnect from 'utils/dbConnect'
import Users from 'models/Users'

import Head from 'next/head'
import Layout from 'components/Layout'
import Card from 'components/Card'

export default function Home({users}) {
    return (
        <>
        <Head>
            <title>Next-Mongoose App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex flex-col space-y-4">
            {users.map((user) => (
                <Card
                    key={user._id}
                    id={user._id}
                    username={user.username}
                    fullname={user.fullname}
                    age={user.age}
                    imageurl={user.imageurl}
                />
            ))}
        </div>
        </>
    )
}

/* Get user data */
export async function getServerSideProps() {
    await dbConnect()

    const result = await Users.find({})
    const users = result.map((doc) => {
        const user = doc.toObject()
        user._id = user._id.toString()
        return user
    })

    return { props: { users: users } }
}

Home.getLayout = (page) => (
    <Layout>
        {page}
    </Layout>
)